#!/bin/bash
# BEGIN_CONF
SQL_SCRIPT=src/test/resources/db.sql
H2_DIR=target/bestdog-1.0-SNAPSHOT/WEB-INF/lib/
DB=~/test
# END_CONF

$JAVA_HOME/bin/java -cp $H2_DIR/h2*.jar org.h2.tools.RunScript -url jdbc:h2:$DB -script $SQL_SCRIPT
$JAVA_HOME/bin/java -cp $H2_DIR/h2*.jar org.h2.tools.Server -tcp -web

